/**
 * P1-32 preparatory slice 2 — item barcodes and packaging identifiers, the database
 * half (P1-32-PRE-100…104).
 *
 * Every assertion is on what `inv.item_identifiers` and its functions accept and
 * refuse, because the application layer only names the field a refusal is about:
 *
 *  - a GTIN, EAN or UPC with a wrong check digit or length is refused by a CHECK;
 *  - `normalized_value` is GENERATED by the same function the resolver calls, so
 *    spaces, hyphens, case and Arabic-Indic digits never decide a match;
 *  - a LIVE code is unique per (tenant, kind, value), and retiring it frees the value;
 *  - the internal code is allocated once per item, carries a valid check digit,
 *    and its number is never handed out again — not after retirement, and not to
 *    two items allocating at the same instant;
 *  - identifiers are tenant-isolated by RLS.
 *
 * Cases run inside rolled-back transactions on the runtime role, except the
 * concurrent allocation and the isolation census, which need COMMITTED rows;
 * `cleanFixtures` removes them.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type { Client } from 'pg';
import {
  adminPool,
  runtimePool,
  runtimeClient,
  setContext,
  ensureTestLogins,
  ensureOrgFixtures,
  cleanFixtures,
  withRolledBackTx,
  withCommittedTx,
  TENANT_A,
  TENANT_B,
  USER_A,
  USER_B,
} from './helpers';
import { seedItem, expectFail } from './p1-10-helpers';

type Q = { query: Client['query'] };

const admin = adminPool();
const runtime = runtimePool();
const ctxA = { tenantId: TENANT_A, userId: USER_A };
const ctxB = { tenantId: TENANT_B, userId: USER_B };

beforeAll(async () => {
  await ensureTestLogins(admin);
  await ensureOrgFixtures(admin);
});
afterAll(async () => {
  await cleanFixtures(admin);
  await admin.end();
  await runtime.end();
});

const one = async <T>(c: Q, sql: string, params: unknown[] = []): Promise<T> =>
  (await c.query(sql, params)).rows[0] as T;

const add = async (
  c: Q,
  item: string,
  kind: string,
  value: string,
  options: { unit?: string | null; pack?: string; primary?: boolean } = {}
): Promise<string> =>
  (
    await one<{ id: string }>(
      c,
      `SELECT inv.add_item_identifier($1,$2,$3,$4,$5::numeric,$6) AS id`,
      [item, kind, value, options.unit ?? null, options.pack ?? '1', options.primary ?? false]
    )
  ).id;

const addSql = `SELECT inv.add_item_identifier($1,$2,$3,NULL,1,false)`;

describe('check digits and normalisation', () => {
  it('accepts well-formed retail codes of every legal length and refuses a wrong check digit', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_cd');
      await add(c, item, 'ean', '4006381333931');
      await add(c, item, 'ean', '96385074');
      await add(c, item, 'upc', '036000291452');
      await add(c, item, 'gtin', '10012345678902');

      // One digit off in each: the mod-10 CHECK refuses all three.
      await expectFail(c, '23514', addSql, [item, 'ean', '4006381333932']);
      await expectFail(c, '23514', addSql, [item, 'upc', '036000291453']);
      await expectFail(c, '23514', addSql, [item, 'gtin', '10012345678903']);
      // A valid EAN-13 is not a UPC: the length is wrong for the kind.
      await expectFail(c, '23514', addSql, [item, 'upc', '4006381333931']);
      // Letters are not a retail code.
      await expectFail(c, '23514', addSql, [item, 'ean', '40063813339AB']);
    });
  });

  it('normalises spaces, hyphens, case and Arabic-Indic digits with one function', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_norm');
      // U+0660..U+0669 are the Arabic-Indic digits 0..9.
      const arabic = '٤٠٠٦٣٨١ 333 931';
      const id = await add(c, item, 'ean', arabic);
      const row = await one<{ value: string; normalized_value: string }>(
        c,
        `SELECT value, normalized_value FROM inv.item_identifiers WHERE id = $1`,
        [id]
      );
      expect(row.normalized_value).toBe('4006381333931');

      const supplier = await add(c, item, 'supplier_code', ' ab-12 cd ');
      const supplierRow = await one<{ normalized_value: string }>(
        c,
        `SELECT normalized_value FROM inv.item_identifiers WHERE id = $1`,
        [supplier]
      );
      expect(supplierRow.normalized_value).toBe('AB12CD');

      const scanned = await one<{ n: string }>(
        c,
        `SELECT inv.normalize_item_identifier('4006-381 333931') AS n`
      );
      expect(scanned.n).toBe(row.normalized_value);
    });
  });

  it('refuses a pack quantity of zero, a blank value, and an entered internal code', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_pack');
      await expectFail(
        c,
        '23514',
        `SELECT inv.add_item_identifier($1,'supplier_code','X1',NULL,0,false)`,
        [item]
      );
      await expectFail(c, '23514', addSql, [item, 'supplier_code', '   ']);
      await expectFail(c, '23514', addSql, [item, 'internal', 'RL0000000017']);
      // A raw INSERT of a malformed internal code is refused by the CHECK as well.
      const unit = (
        await one<{ uom_id: string }>(c, `SELECT uom_id FROM inv.item_master WHERE id = $1`, [item])
      ).uom_id;
      await expectFail(
        c,
        '23514',
        `INSERT INTO inv.item_identifiers (tenant_id, item_id, identifier_kind, value, unit_id, created_by)
         VALUES ($1,$2,'internal','RL0000000018',$3,$4)`,
        [TENANT_A, item, unit, USER_A]
      );
      // A case code carries its pack size.
      const caseCode = await add(c, item, 'gtin', '10012345678902', { pack: '12' });
      const row = await one<{ pack_quantity: string }>(
        c,
        `SELECT pack_quantity::text FROM inv.item_identifiers WHERE id = $1`,
        [caseCode]
      );
      expect(row.pack_quantity).toBe('12.000');
    });
  });
});

describe('uniqueness, primary and retirement', () => {
  it('keeps one LIVE row per kind and value, and frees the value on retirement', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_uq1');
      const { item: other } = await seedItem(c, 'odinv_uq2');
      const first = await add(c, item, 'ean', '4006381333931');
      // The same code on another item — or spelled differently — is still a duplicate.
      await expectFail(c, '23505', addSql, [other, 'ean', '4006 381 333931']);
      // A different kind is a different identifier.
      await add(c, other, 'supplier_code', '4006381333931');

      await c.query(`SELECT inv.retire_item_identifier($1)`, [first]);
      // Retiring twice is a no-op, not an error.
      await c.query(`SELECT inv.retire_item_identifier($1)`, [first]);
      const reused = await add(c, other, 'ean', '4006381333931');
      expect(reused).not.toBe(first);

      const rows = await c.query<{ id: string; retired: boolean }>(
        `SELECT id, retired_at IS NOT NULL AS retired FROM inv.item_identifiers
          WHERE normalized_value = '4006381333931' AND identifier_kind = 'ean' ORDER BY created_at, id`
      );
      expect(rows.rows).toHaveLength(2);
      expect(rows.rows.find((r) => r.id === first)?.retired).toBe(true);
    });
  });

  it('demotes the previous primary, and freezes a retired identifier', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_prim');
      const a = await add(c, item, 'ean', '4006381333931', { primary: true });
      const b = await add(c, item, 'upc', '036000291452', { primary: true });
      const primaries = await c.query<{ id: string }>(
        `SELECT id FROM inv.item_identifiers WHERE item_id = $1 AND is_primary AND retired_at IS NULL`,
        [item]
      );
      expect(primaries.rows.map((r) => r.id)).toEqual([b]);

      await c.query(`SELECT inv.retire_item_identifier($1)`, [a]);
      await expectFail(
        c,
        '23514',
        `UPDATE inv.item_identifiers SET retired_at = NULL, retired_by = NULL WHERE id = $1`,
        [a]
      );
      await expectFail(
        c,
        '23514',
        `UPDATE inv.item_identifiers SET value = '96385074' WHERE id = $1`,
        [b]
      );
    });
  });

  it('refuses a new identifier on an archived item and a unit of another tenant', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_arch');
      await c.query(`UPDATE inv.item_master SET lifecycle_status = 'archived' WHERE id = $1`, [
        item,
      ]);
      await expectFail(c, '23514', addSql, [item, 'supplier_code', 'SUP-1']);
    });
    const foreignUnit = (
      await admin.query<{ id: string }>(
        `INSERT INTO inv.units_of_measure (scope, tenant_id, code, name, dimension, created_by)
         VALUES ('tenant',$1,'u_odinv_foreign','Foreign unit','count',$2) RETURNING id`,
        [TENANT_B, USER_B]
      )
    ).rows[0]!.id;
    try {
      await withRolledBackTx(runtime, ctxA, async (c) => {
        const { item } = await seedItem(c, 'odinv_unit');
        // RLS hides the other tenant's unit from the guard, which then reports it
        // absent (23503); a unit that WAS visible but foreign is the 23514 branch.
        await expectFail(
          c,
          ['23503', '23514'],
          `SELECT inv.add_item_identifier($1,'supplier_code','SUP-2',$2,1,false)`,
          [item, foreignUnit]
        );
      });
    } finally {
      await admin.query(`DELETE FROM inv.units_of_measure WHERE id = $1`, [foreignUnit]);
    }
  });
});

describe('internal barcode allocation', () => {
  it('allocates RL + nine digits + a valid check digit once per item, and becomes primary', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_int1');
      const first = (
        await one<{ id: string }>(c, `SELECT inv.assign_internal_barcode($1) AS id`, [item])
      ).id;
      const again = (
        await one<{ id: string }>(c, `SELECT inv.assign_internal_barcode($1) AS id`, [item])
      ).id;
      expect(again).toBe(first);

      const row = await one<{ value: string; is_primary: boolean; ok: boolean; pack: string }>(
        c,
        `SELECT value, is_primary, inv.item_identifier_is_well_formed('internal', normalized_value) AS ok,
                pack_quantity::text AS pack
           FROM inv.item_identifiers WHERE id = $1`,
        [first]
      );
      expect(row.value).toMatch(/^RL\d{10}$/);
      expect(row.ok).toBe(true);
      expect(row.is_primary).toBe(true);
      expect(row.pack).toBe('1.000');
      const count = await one<{ n: string }>(
        c,
        `SELECT count(*)::text AS n FROM inv.item_identifiers WHERE item_id = $1 AND identifier_kind = 'internal'`,
        [item]
      );
      expect(count.n).toBe('1');
    });
  });

  it('never reallocates a retired number', async () => {
    await withRolledBackTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_int2');
      const first = (
        await one<{ id: string }>(c, `SELECT inv.assign_internal_barcode($1) AS id`, [item])
      ).id;
      await c.query(`SELECT inv.retire_item_identifier($1)`, [first]);
      const second = (
        await one<{ id: string }>(c, `SELECT inv.assign_internal_barcode($1) AS id`, [item])
      ).id;
      expect(second).not.toBe(first);
      // Keyed on which row is LIVE, not on insertion order: both rows are written
      // in one transaction, so they share `created_at` to the microsecond and an
      // `ORDER BY created_at, id` tie-break is the random UUID — which decides
      // nothing about allocation and would make this assertion a coin flip.
      const numbers = await c.query<{ id: string; n: string; live: boolean }>(
        `SELECT id, substr(normalized_value, 3, 9) AS n, (retired_at IS NULL) AS live
           FROM inv.item_identifiers WHERE id = ANY($1)`,
        [[first, second]]
      );
      const retired = numbers.rows.find((r) => !r.live);
      const live = numbers.rows.find((r) => r.live);
      expect(retired?.id).toBe(first);
      expect(live?.id).toBe(second);
      expect(BigInt(live!.n) > BigInt(retired!.n)).toBe(true);
    });
  });

  it('gives two items allocating at the same instant two different numbers', async () => {
    const items = await withCommittedTx(runtime, ctxA, async (c) => {
      const { item: one1 } = await seedItem(c, 'odinv_conc1');
      const { item: two2 } = await seedItem(c, 'odinv_conc2');
      return [one1, two2];
    });
    const allocate = async (item: string): Promise<string> => {
      const client = runtimeClient();
      await client.connect();
      try {
        await client.query('BEGIN');
        await setContext(client, ctxA);
        const result = await client.query<{ id: string }>(
          `SELECT inv.assign_internal_barcode($1) AS id`,
          [item]
        );
        await client.query('COMMIT');
        return result.rows[0]!.id;
      } finally {
        await client.end();
      }
    };
    const ids = await Promise.all(items.map((item) => allocate(item)));
    const values = await admin.query<{ normalized_value: string }>(
      `SELECT normalized_value FROM inv.item_identifiers WHERE id = ANY($1)`,
      [ids]
    );
    expect(new Set(values.rows.map((r) => r.normalized_value)).size).toBe(2);
  });
});

describe('tenant isolation', () => {
  it('hides tenant A identifiers from tenant B, and B cannot attach one to A item', async () => {
    const seeded = await withCommittedTx(runtime, ctxA, async (c) => {
      const { item } = await seedItem(c, 'odinv_iso');
      const id = await add(c, item, 'supplier_code', 'ODINV-ISO-1');
      return { item, id };
    });
    await withRolledBackTx(runtime, ctxB, async (c) => {
      const visible = await one<{ n: string }>(
        c,
        `SELECT count(*)::text AS n FROM inv.item_identifiers WHERE id = $1 OR item_id = $2`,
        [seeded.id, seeded.item]
      );
      expect(visible.n).toBe('0');
      // The item itself is invisible to B, so the function reports it absent.
      await expectFail(c, '23503', addSql, [seeded.item, 'supplier_code', 'ODINV-ISO-2']);
      await expectFail(c, '23503', `SELECT inv.retire_item_identifier($1)`, [seeded.id]);
    });
  });
});
