/**
 * GENERATED — do not edit by hand.
 *
 * Produced by `scripts/ci/generate-idempotent-operations.mjs` from the published
 * contract `docs/api/openapi.v1.json`, and reconciled against it by
 * `npm run validate:idempotent-operations`.
 *
 * ## What this is for (`P1-27-INT-003`)
 *
 * The backend requires an `Idempotency-Key` header on every operation it
 * registers as idempotent, and answers `400 ERR-INT-002` without one — before
 * authorization is evaluated. That set is NOT "the POST operations": it is
 * currently 156 operations (PATCH 3, POST 147, PUT 6).
 *
 * The client used to infer the answer from the HTTP method, which was wrong for
 * every non-POST member of that set. This table is the contract instead of a
 * guess, and the gate is what keeps it true.
 *
 * ## The audit class (`P1-27-SEC-004`)
 *
 * `auditClass` is the published `x-audit-class` extension, which
 * `openapi/document.ts:228` writes from the operation registration. Before it
 * was carried here, `auditClass` existed in `apps/web` only inside docblocks —
 * thirteen of them stating which class a write declares, none of them checkable
 * — because the Web tier held no data from which one could be derived.
 *
 * Currently approval 13, export 1, financial 13, none 138, privileged 167, security 13.
 *
 * `(absent)` above would mean an operation the document publishes with NO audit
 * class. It is emitted as the empty string rather than defaulted to `none`,
 * because a defaulted value is indistinguishable from a declared one and the
 * whole point of the Web assertions is to fail on the undeclared case.
 */

/** One published operation, keyed by the template the client calls. */
export interface PublishedOperation {
  /** Path template WITHOUT the `/api/v1` prefix — the client holds that. */
  readonly template: string;
  readonly method: string;
  readonly operationId: string;
  /** True when the backend will refuse the request without a key. */
  readonly idempotent: boolean;
  /**
   * The published `x-audit-class`: `'none'` when the operation writes no audit
   * event, otherwise the class of event it writes. Empty string when the
   * document publishes the operation without the extension at all — which is
   * a defect, not a default.
   */
  readonly auditClass: string;
}

/** Every operation the contract publishes. 345 of them. */
export const PUBLISHED_OPERATIONS: readonly PublishedOperation[] = Object.freeze([
  {
    template: '/additional-work/{requestId}/approval',
    method: 'GET',
    operationId: 'wo.additional-work-approval-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/additional-work/{requestId}/approval',
    method: 'POST',
    operationId: 'wo.additional-work-approval',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/additional-work/{requestId}/detail',
    method: 'GET',
    operationId: 'wo.additional-work-detail-read',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/additional-work/{requestId}/detail',
    method: 'PUT',
    operationId: 'wo.additional-work-detail-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/additional-work/{requestId}/fulfillment',
    method: 'POST',
    operationId: 'wo.additional-work-fulfillment',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/additional-work/{requestId}/withdrawal',
    method: 'POST',
    operationId: 'wo.additional-work-withdraw',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/appointment-types',
    method: 'GET',
    operationId: 'apt.catalogue-appointment-type-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/appointment-types',
    method: 'POST',
    operationId: 'apt.catalogue-appointment-type-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/appointment-types/{appointmentTypeId}',
    method: 'PATCH',
    operationId: 'apt.catalogue-appointment-type-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/appointment-types/{appointmentTypeId}/status',
    method: 'POST',
    operationId: 'apt.catalogue-appointment-type-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/cancellation-reasons',
    method: 'GET',
    operationId: 'apt.catalogue-cancellation-reason-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/cancellation-reasons',
    method: 'POST',
    operationId: 'apt.catalogue-cancellation-reason-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/cancellation-reasons/{cancellationReasonId}',
    method: 'PATCH',
    operationId: 'apt.catalogue-cancellation-reason-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/cancellation-reasons/{cancellationReasonId}/status',
    method: 'POST',
    operationId: 'apt.catalogue-cancellation-reason-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/management/appointment-types',
    method: 'GET',
    operationId: 'apt.catalogue-appointment-type-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/management/cancellation-reasons',
    method: 'GET',
    operationId: 'apt.catalogue-cancellation-reason-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/management/source-channels',
    method: 'GET',
    operationId: 'apt.catalogue-source-channel-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/source-channels',
    method: 'GET',
    operationId: 'apt.catalogue-source-channel-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointment-catalogue/source-channels',
    method: 'POST',
    operationId: 'apt.catalogue-source-channel-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/source-channels/{sourceChannelId}',
    method: 'PATCH',
    operationId: 'apt.catalogue-source-channel-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/appointment-catalogue/source-channels/{sourceChannelId}/status',
    method: 'POST',
    operationId: 'apt.catalogue-source-channel-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointments',
    method: 'GET',
    operationId: 'apt.appointment-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointments',
    method: 'POST',
    operationId: 'apt.appointment-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointments/{appointmentId}',
    method: 'GET',
    operationId: 'apt.appointment-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/appointments/{appointmentId}/cancel',
    method: 'POST',
    operationId: 'apt.appointment-cancel',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointments/{appointmentId}/no-show',
    method: 'POST',
    operationId: 'apt.appointment-no-show',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/appointments/{appointmentId}/reschedule',
    method: 'POST',
    operationId: 'apt.appointment-reschedule',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/assignments/{assignmentId}/end',
    method: 'POST',
    operationId: 'wo.job-assignment-end',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/attachments/categories',
    method: 'GET',
    operationId: 'shared.document-category-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/attachments/documents/{documentId}',
    method: 'GET',
    operationId: 'shared.document-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/attachments/documents/{documentId}/download-authorizations',
    method: 'POST',
    operationId: 'shared.attachment-download-authorize',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/attachments/documents/{documentId}/links',
    method: 'POST',
    operationId: 'shared.attachment-link-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/attachments/documents/{documentId}/retention-evaluations',
    method: 'POST',
    operationId: 'shared.document-retention-evaluate',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/attachments/links/{linkId}',
    method: 'DELETE',
    operationId: 'shared.attachment-link-withdraw',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/attachments/upload-authorizations',
    method: 'POST',
    operationId: 'shared.attachment-upload-authorize',
    idempotent: true,
    auditClass: 'security',
  },
  {
    template: '/attachments/versions',
    method: 'POST',
    operationId: 'shared.attachment-version-register',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/attachments/versions/{versionId}',
    method: 'GET',
    operationId: 'shared.document-version-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/attachments/versions/{versionId}/rejection',
    method: 'POST',
    operationId: 'shared.attachment-version-reject',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/audit-events',
    method: 'GET',
    operationId: 'iam.audit-event-list',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/audit-events/{recordId}',
    method: 'GET',
    operationId: 'iam.audit-event-detail',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/auth/login',
    method: 'POST',
    operationId: 'iam.auth-login',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/auth/logout',
    method: 'POST',
    operationId: 'iam.auth-logout',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/auth/password-reset',
    method: 'POST',
    operationId: 'iam.auth-password-reset',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/auth/password-reset/completion',
    method: 'POST',
    operationId: 'iam.auth-password-reset-completion',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/auth/session',
    method: 'GET',
    operationId: 'iam.auth-session',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/credit-notes/{creditNoteId}/approval',
    method: 'POST',
    operationId: 'sal.credit-note-approve',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/customer-duplicates',
    method: 'GET',
    operationId: 'crm.duplicate-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customer-duplicates/{candidateId}/review',
    method: 'POST',
    operationId: 'crm.duplicate-review',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customer-supplied-parts',
    method: 'POST',
    operationId: 'inv.customer-supplied-part-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers',
    method: 'GET',
    operationId: 'crm.customer-search',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}',
    method: 'GET',
    operationId: 'crm.customer-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/addresses',
    method: 'GET',
    operationId: 'crm.address-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/addresses',
    method: 'POST',
    operationId: 'crm.address-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/alerts',
    method: 'GET',
    operationId: 'crm.alert-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/alerts',
    method: 'POST',
    operationId: 'crm.alert-raise',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/consents',
    method: 'GET',
    operationId: 'crm.consent-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/consents',
    method: 'POST',
    operationId: 'crm.consent-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/contacts',
    method: 'GET',
    operationId: 'crm.contact-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/contacts',
    method: 'POST',
    operationId: 'crm.contact-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/duplicate-scans',
    method: 'POST',
    operationId: 'crm.duplicate-scan',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/history',
    method: 'GET',
    operationId: 'crm.customer-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/merge',
    method: 'POST',
    operationId: 'crm.customer-merge',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/notes',
    method: 'GET',
    operationId: 'crm.note-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/notes',
    method: 'POST',
    operationId: 'crm.note-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/preferences',
    method: 'GET',
    operationId: 'crm.preference-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/preferences',
    method: 'PUT',
    operationId: 'crm.preference-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/restrictions',
    method: 'GET',
    operationId: 'crm.restriction-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/restrictions',
    method: 'POST',
    operationId: 'crm.restriction-impose',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/status',
    method: 'PUT',
    operationId: 'crm.customer-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/tags',
    method: 'GET',
    operationId: 'crm.tag-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/tags',
    method: 'POST',
    operationId: 'crm.tag-assign',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/{customerId}/timeline',
    method: 'GET',
    operationId: 'crm.customer-timeline',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/vehicles',
    method: 'GET',
    operationId: 'crm.customer-vehicle-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/customers/{customerId}/vehicles',
    method: 'POST',
    operationId: 'crm.vehicle-link',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/companies',
    method: 'POST',
    operationId: 'crm.company-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/customers/individuals',
    method: 'POST',
    operationId: 'crm.individual-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/damaged-stock',
    method: 'POST',
    operationId: 'inv.damaged-stock-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries',
    method: 'POST',
    operationId: 'sal.delivery-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries/{deliveryId}/authorized-receiver',
    method: 'POST',
    operationId: 'sal.delivery-receiver-verify',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries/{deliveryId}/checklist-results',
    method: 'POST',
    operationId: 'sal.delivery-checklist-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries/{deliveryId}/completion',
    method: 'POST',
    operationId: 'sal.delivery-complete',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries/{deliveryId}/eligibility',
    method: 'GET',
    operationId: 'sal.delivery-eligibility-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/deliveries/{deliveryId}/signatures',
    method: 'POST',
    operationId: 'sal.delivery-signature-attach',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/deliveries/{deliveryId}/warranties',
    method: 'POST',
    operationId: 'wty.warranty-generate',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/exports/authorizations',
    method: 'POST',
    operationId: 'shared.export-authorize',
    idempotent: false,
    auditClass: 'export',
  },
  {
    template: '/exports/resources',
    method: 'GET',
    operationId: 'shared.export-catalogue',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/external-purchase-parts',
    method: 'POST',
    operationId: 'inv.external-purchase-part-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/health/live',
    method: 'GET',
    operationId: 'shared.health-live',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/health/ready',
    method: 'GET',
    operationId: 'shared.health-ready',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/approval-limits',
    method: 'GET',
    operationId: 'iam.approval-limit-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/approval-limits',
    method: 'POST',
    operationId: 'iam.approval-limit-create',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/iam/approval-limits/{limitId}',
    method: 'PATCH',
    operationId: 'iam.approval-limit-end',
    idempotent: false,
    auditClass: 'approval',
  },
  {
    template: '/iam/grants',
    method: 'POST',
    operationId: 'iam.grant-issue',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/iam/grants/{grantId}',
    method: 'DELETE',
    operationId: 'iam.grant-revoke',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/iam/grants/{grantId}/scopes',
    method: 'GET',
    operationId: 'iam.grant-scope-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/grants/{grantId}/scopes',
    method: 'POST',
    operationId: 'iam.grant-scope-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/iam/grants/{grantId}/scopes/{scopeId}',
    method: 'DELETE',
    operationId: 'iam.grant-scope-remove',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/invitations',
    method: 'POST',
    operationId: 'iam.invitation-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/iam/invitations/{userId}',
    method: 'DELETE',
    operationId: 'iam.invitation-cancel',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/invitations/{userId}/activation',
    method: 'POST',
    operationId: 'iam.invitation-activate',
    idempotent: true,
    auditClass: 'security',
  },
  {
    template: '/iam/permissions',
    method: 'GET',
    operationId: 'iam.permission-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/roles',
    method: 'GET',
    operationId: 'iam.role-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/roles',
    method: 'POST',
    operationId: 'iam.role-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/iam/roles/{roleId}',
    method: 'PATCH',
    operationId: 'iam.role-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/roles/{roleId}/permissions',
    method: 'GET',
    operationId: 'iam.role-permission-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/roles/{roleId}/permissions',
    method: 'POST',
    operationId: 'iam.role-permission-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/iam/roles/{roleId}/permissions/{mappingId}',
    method: 'DELETE',
    operationId: 'iam.role-permission-remove',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/roles/{roleId}/permissions/{mappingId}',
    method: 'PATCH',
    operationId: 'iam.role-permission-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/users',
    method: 'GET',
    operationId: 'iam.user-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/users/{userId}',
    method: 'GET',
    operationId: 'iam.user-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/users/{userId}',
    method: 'PATCH',
    operationId: 'iam.user-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/iam/users/{userId}/sessions',
    method: 'DELETE',
    operationId: 'iam.user-session-revoke-all',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/iam/users/{userId}/sessions',
    method: 'GET',
    operationId: 'iam.user-session-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/iam/users/{userId}/status',
    method: 'POST',
    operationId: 'iam.user-status-change',
    idempotent: true,
    auditClass: 'security',
  },
  {
    template: '/inspection-templates',
    method: 'GET',
    operationId: 'dia.template-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/inspection-templates',
    method: 'POST',
    operationId: 'dia.template-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspection-templates/{templateId}',
    method: 'GET',
    operationId: 'dia.template-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/inspection-templates/{templateId}',
    method: 'PATCH',
    operationId: 'dia.template-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/inspection-templates/{templateId}/versions',
    method: 'POST',
    operationId: 'dia.template-version-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}',
    method: 'GET',
    operationId: 'dia.diagnostic-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/inspections/{inspectionId}/completion',
    method: 'POST',
    operationId: 'dia.diagnostic-complete',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/dtcs',
    method: 'POST',
    operationId: 'dia.diagnostic-dtc-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/evidence',
    method: 'POST',
    operationId: 'dia.diagnostic-evidence-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/findings',
    method: 'POST',
    operationId: 'dia.diagnostic-finding-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/history',
    method: 'GET',
    operationId: 'dia.diagnostic-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/inspections/{inspectionId}/items/{templateItemId}',
    method: 'PUT',
    operationId: 'dia.diagnostic-item-result',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/measurements',
    method: 'POST',
    operationId: 'dia.diagnostic-measurement-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/recommendations',
    method: 'POST',
    operationId: 'dia.diagnostic-recommendation-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inspections/{inspectionId}/reviews',
    method: 'POST',
    operationId: 'dia.diagnostic-review',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/inspections/{inspectionId}/transition',
    method: 'POST',
    operationId: 'dia.diagnostic-transition',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/inventory-reconciliations',
    method: 'GET',
    operationId: 'inv.inventory-reconciliation-read',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/invoices',
    method: 'POST',
    operationId: 'sal.invoice-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/invoices/{invoiceId}',
    method: 'GET',
    operationId: 'sal.invoice-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/invoices/{invoiceId}/cancellation',
    method: 'POST',
    operationId: 'sal.invoice-cancel',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/invoices/{invoiceId}/credit-notes',
    method: 'POST',
    operationId: 'sal.credit-note-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/invoices/{invoiceId}/issuance',
    method: 'POST',
    operationId: 'sal.invoice-issue',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/invoices/{invoiceId}/outstanding',
    method: 'GET',
    operationId: 'sal.invoice-outstanding-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/items',
    method: 'GET',
    operationId: 'inv.item-search',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs',
    method: 'GET',
    operationId: 'wo.job-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}',
    method: 'GET',
    operationId: 'wo.job-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}',
    method: 'PATCH',
    operationId: 'wo.job-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/assignments',
    method: 'GET',
    operationId: 'wo.job-assignment-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/assignments',
    method: 'POST',
    operationId: 'wo.job-assignment-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/evidence',
    method: 'GET',
    operationId: 'wo.job-evidence-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/evidence',
    method: 'POST',
    operationId: 'wo.job-evidence-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/history',
    method: 'GET',
    operationId: 'wo.job-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/inspection-templates',
    method: 'GET',
    operationId: 'dia.template-version-list-publishable',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/inspections',
    method: 'GET',
    operationId: 'dia.diagnostic-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/inspections',
    method: 'POST',
    operationId: 'dia.diagnostic-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/labor-sessions',
    method: 'GET',
    operationId: 'tech.labor-session-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/labor-sessions',
    method: 'POST',
    operationId: 'tech.labor-session-start',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/reassignments',
    method: 'POST',
    operationId: 'wo.job-reassignment',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/transition',
    method: 'POST',
    operationId: 'wo.job-transition',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/jobs/{jobId}/work-logs',
    method: 'GET',
    operationId: 'wo.job-work-log-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/jobs/{jobId}/work-logs',
    method: 'POST',
    operationId: 'wo.job-work-log-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/labor-sessions/{sessionId}/corrections',
    method: 'POST',
    operationId: 'tech.labor-session-correct',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/labor-sessions/{sessionId}/stop',
    method: 'POST',
    operationId: 'tech.labor-session-stop',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/message-templates',
    method: 'POST',
    operationId: 'shared.template-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/message-templates/{templateId}',
    method: 'PATCH',
    operationId: 'shared.template-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/message-templates/{templateId}/active-version',
    method: 'PUT',
    operationId: 'shared.template-activation-set',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/message-templates/{templateId}/versions',
    method: 'POST',
    operationId: 'shared.template-version-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/meta/ping',
    method: 'GET',
    operationId: 'meta.ping',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/notifications',
    method: 'GET',
    operationId: 'shared.notification-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/notifications',
    method: 'POST',
    operationId: 'shared.notification-enqueue',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/notifications/{notificationId}',
    method: 'GET',
    operationId: 'shared.notification-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/notifications/{notificationId}/deliveries',
    method: 'GET',
    operationId: 'shared.notification-delivery-list',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/opening-inventory-batches',
    method: 'POST',
    operationId: 'inv.opening-batch-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/opening-inventory-batches/{batchId}/approval',
    method: 'POST',
    operationId: 'inv.opening-batch-approve',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/opening-inventory-batches/{batchId}/lines',
    method: 'POST',
    operationId: 'inv.opening-batch-line-create',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/branches',
    method: 'GET',
    operationId: 'org.branch-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/branches/{branchId}',
    method: 'PATCH',
    operationId: 'org.branch-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/org/branches/{branchId}/settings',
    method: 'GET',
    operationId: 'iam.branch-settings-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/branches/{branchId}/settings',
    method: 'POST',
    operationId: 'iam.branch-settings-write',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/org/companies',
    method: 'GET',
    operationId: 'org.company-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/companies/{companyId}',
    method: 'PATCH',
    operationId: 'org.company-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/org/companies/{companyId}/settings',
    method: 'GET',
    operationId: 'iam.company-settings-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/companies/{companyId}/settings',
    method: 'POST',
    operationId: 'iam.company-settings-write',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/org/companies/{companyId}/status',
    method: 'POST',
    operationId: 'org.company-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/org/departments',
    method: 'GET',
    operationId: 'org.department-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/departments',
    method: 'POST',
    operationId: 'org.department-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/org/departments/{departmentId}',
    method: 'PATCH',
    operationId: 'org.department-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/org/tenant',
    method: 'GET',
    operationId: 'iam.tenant-settings-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/org/tenant',
    method: 'PATCH',
    operationId: 'iam.tenant-settings-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/organization/branches/{branchId}/status',
    method: 'GET',
    operationId: 'shared.branch-status-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/organization/branches/{branchId}/status',
    method: 'POST',
    operationId: 'shared.branch-status-change',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/payment-methods',
    method: 'GET',
    operationId: 'sal.payment-method-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/payments',
    method: 'POST',
    operationId: 'sal.payment-record',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/payments/{paymentId}',
    method: 'GET',
    operationId: 'sal.receipt-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/payments/{paymentId}/allocations',
    method: 'POST',
    operationId: 'sal.payment-allocate',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/platform/organizations',
    method: 'GET',
    operationId: 'platform.organization-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/platform/organizations',
    method: 'POST',
    operationId: 'platform.organization-provision',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/platform/organizations/{tenantId}/status',
    method: 'POST',
    operationId: 'platform.organization-lifecycle',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/price-lists',
    method: 'GET',
    operationId: 'svc.price-list-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/price-lists',
    method: 'POST',
    operationId: 'svc.price-list-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/price-lists/{priceListId}/versions',
    method: 'POST',
    operationId: 'svc.price-list-version-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/price-lists/{priceListId}/versions/{versionId}/publication',
    method: 'POST',
    operationId: 'svc.price-list-version-publish',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/price-lists/{priceListId}/versions/{versionId}/rules',
    method: 'POST',
    operationId: 'svc.price-rule-record',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/prices',
    method: 'GET',
    operationId: 'svc.price-resolve',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/quality-controls',
    method: 'GET',
    operationId: 'qms.qc-record-branch-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/quality-controls/{recordId}',
    method: 'GET',
    operationId: 'qms.qc-record-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/quality-controls/{recordId}/checks/{qcCheckId}',
    method: 'PUT',
    operationId: 'qms.qc-check-result',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/quality-controls/{recordId}/finalization',
    method: 'POST',
    operationId: 'qms.qc-record-finalize',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/quotation-items/{quotationItemId}/decisions',
    method: 'POST',
    operationId: 'quo.quotation-item-decide',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/quotation-revisions/{revisionId}/decisions',
    method: 'POST',
    operationId: 'quo.quotation-revision-decide',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/quotations',
    method: 'POST',
    operationId: 'quo.quotation-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/quotations/{quotationId}',
    method: 'GET',
    operationId: 'quo.quotation-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/quotations/{quotationId}/issue',
    method: 'POST',
    operationId: 'quo.quotation-issue',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/quotations/{quotationId}/revisions',
    method: 'POST',
    operationId: 'quo.quotation-revision-create',
    idempotent: true,
    auditClass: 'financial',
  },
  {
    template: '/reception-catalogue/capture-policies',
    method: 'GET',
    operationId: 'rec.catalogue-capture-policy-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/capture-policies',
    method: 'POST',
    operationId: 'rec.catalogue-capture-policy-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/damage-map-templates',
    method: 'GET',
    operationId: 'rec.catalogue-damage-map-template-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/damage-map-templates',
    method: 'POST',
    operationId: 'rec.catalogue-damage-map-template-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/damage-map-templates/{templateId}',
    method: 'GET',
    operationId: 'rec.catalogue-damage-map-template-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/damage-map-templates/{templateId}/status',
    method: 'POST',
    operationId: 'rec.catalogue-damage-map-template-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/damage-map-templates/{templateId}/versions',
    method: 'POST',
    operationId: 'rec.catalogue-damage-map-template-version-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/fuel-levels',
    method: 'GET',
    operationId: 'rec.catalogue-fuel-level-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/fuel-levels',
    method: 'POST',
    operationId: 'rec.catalogue-fuel-level-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/fuel-levels/{fuelLevelId}',
    method: 'PATCH',
    operationId: 'rec.catalogue-fuel-level-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/fuel-levels/{fuelLevelId}/status',
    method: 'POST',
    operationId: 'rec.catalogue-fuel-level-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/management/fuel-levels',
    method: 'GET',
    operationId: 'rec.catalogue-fuel-level-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/management/refusal-reasons',
    method: 'GET',
    operationId: 'rec.catalogue-refusal-reason-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/management/visit-reasons',
    method: 'GET',
    operationId: 'rec.catalogue-visit-reason-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/management/warning-light-codes',
    method: 'GET',
    operationId: 'rec.catalogue-warning-light-code-management-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/receiving-employees',
    method: 'GET',
    operationId: 'rec.receiving-employee-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/refusal-reasons',
    method: 'GET',
    operationId: 'rec.catalogue-refusal-reason-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/refusal-reasons',
    method: 'POST',
    operationId: 'rec.catalogue-refusal-reason-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/refusal-reasons/{refusalReasonId}',
    method: 'PATCH',
    operationId: 'rec.catalogue-refusal-reason-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/refusal-reasons/{refusalReasonId}/status',
    method: 'POST',
    operationId: 'rec.catalogue-refusal-reason-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/visit-reasons',
    method: 'GET',
    operationId: 'rec.catalogue-visit-reason-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/visit-reasons',
    method: 'POST',
    operationId: 'rec.catalogue-visit-reason-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/visit-reasons/{visitReasonId}',
    method: 'PATCH',
    operationId: 'rec.catalogue-visit-reason-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/visit-reasons/{visitReasonId}/status',
    method: 'POST',
    operationId: 'rec.catalogue-visit-reason-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/warning-light-codes',
    method: 'GET',
    operationId: 'rec.catalogue-warning-light-code-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reception-catalogue/warning-light-codes',
    method: 'POST',
    operationId: 'rec.catalogue-warning-light-code-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/warning-light-codes/{warningLightCodeId}',
    method: 'PATCH',
    operationId: 'rec.catalogue-warning-light-code-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/reception-catalogue/warning-light-codes/{warningLightCodeId}/status',
    method: 'POST',
    operationId: 'rec.catalogue-warning-light-code-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions',
    method: 'GET',
    operationId: 'rec.reception-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions',
    method: 'POST',
    operationId: 'rec.reception-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}',
    method: 'GET',
    operationId: 'rec.reception-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/approve',
    method: 'POST',
    operationId: 'rec.reception-approve',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/receptions/{receptionId}/authorizations',
    method: 'GET',
    operationId: 'rec.reception-authorization-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/authorizations',
    method: 'POST',
    operationId: 'rec.reception-authorization',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/receptions/{receptionId}/capture-overrides',
    method: 'POST',
    operationId: 'rec.reception-capture-override',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/close-without-work',
    method: 'POST',
    operationId: 'rec.reception-close-without-work',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/condition-evidence',
    method: 'GET',
    operationId: 'rec.reception-condition-evidence-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/condition-evidence',
    method: 'POST',
    operationId: 'rec.reception-condition-evidence',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/convert-to-work-order',
    method: 'POST',
    operationId: 'rec.reception-convert-to-work-order',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/evidence-bindings',
    method: 'GET',
    operationId: 'rec.reception-evidence-binding-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/evidence-bindings',
    method: 'POST',
    operationId: 'rec.reception-evidence-binding',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/evidence-bindings/{bindingId}/finalization',
    method: 'POST',
    operationId: 'rec.reception-evidence-binding-finalize',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/history',
    method: 'GET',
    operationId: 'rec.reception-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/party-roles',
    method: 'GET',
    operationId: 'rec.reception-party-role-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/party-roles',
    method: 'POST',
    operationId: 'rec.reception-party-role',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/refusals',
    method: 'POST',
    operationId: 'rec.reception-refusal',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/refuse',
    method: 'POST',
    operationId: 'rec.reception-refuse',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/signatures',
    method: 'GET',
    operationId: 'rec.reception-signature-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/receptions/{receptionId}/signatures',
    method: 'POST',
    operationId: 'rec.reception-signature',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/receptions/{receptionId}/signatures/{signatureId}/events',
    method: 'POST',
    operationId: 'rec.reception-signature-event',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/reports',
    method: 'GET',
    operationId: 'rpt.report-catalogue',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/reports/{reportCode}',
    method: 'GET',
    operationId: 'rpt.report-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/rework-links/{reworkLinkId}',
    method: 'GET',
    operationId: 'qms.rework-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/rework-links/{reworkLinkId}/cost',
    method: 'GET',
    operationId: 'qms.rework-cost-read',
    idempotent: false,
    auditClass: 'security',
  },
  {
    template: '/rework-links/{reworkLinkId}/cost',
    method: 'PUT',
    operationId: 'qms.rework-cost-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/rework-links/{reworkLinkId}/sign-off',
    method: 'POST',
    operationId: 'qms.rework-sign-off',
    idempotent: true,
    auditClass: 'approval',
  },
  {
    template: '/services',
    method: 'GET',
    operationId: 'svc.service-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/services',
    method: 'POST',
    operationId: 'svc.service-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/services/{serviceId}',
    method: 'PATCH',
    operationId: 'svc.service-update',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/services/{serviceId}/branch-availability',
    method: 'POST',
    operationId: 'svc.branch-availability-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/services/{serviceId}/versions/{versionId}/publication',
    method: 'POST',
    operationId: 'svc.service-version-publish',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/stock-availability',
    method: 'GET',
    operationId: 'inv.stock-availability-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/stock-issues',
    method: 'POST',
    operationId: 'inv.stock-issue-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/stock-movements',
    method: 'GET',
    operationId: 'inv.stock-movement-list',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/stock-reservations',
    method: 'POST',
    operationId: 'inv.stock-reservation-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/stock-reservations/{reservationId}/release',
    method: 'POST',
    operationId: 'inv.stock-reservation-release',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/stock-returns',
    method: 'POST',
    operationId: 'inv.stock-return-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/technicians',
    method: 'GET',
    operationId: 'tech.technician-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/technicians',
    method: 'POST',
    operationId: 'tech.technician-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}',
    method: 'GET',
    operationId: 'tech.technician-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/technicians/{technicianProfileId}',
    method: 'PATCH',
    operationId: 'tech.technician-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/availability',
    method: 'POST',
    operationId: 'tech.technician-availability-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/availability/{availabilityId}',
    method: 'DELETE',
    operationId: 'tech.technician-availability-withdraw',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/certifications',
    method: 'POST',
    operationId: 'tech.technician-certification-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/certifications/{certificationId}',
    method: 'PATCH',
    operationId: 'tech.technician-certification-update',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/certifications/{certificationId}/detail',
    method: 'PUT',
    operationId: 'tech.technician-certification-detail-record',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/queue',
    method: 'GET',
    operationId: 'tech.technician-queue',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/technicians/{technicianProfileId}/skills/{skillId}',
    method: 'DELETE',
    operationId: 'tech.technician-skill-withdraw',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/{technicianProfileId}/skills/{skillId}',
    method: 'PUT',
    operationId: 'tech.technician-skill-set',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/technicians/available',
    method: 'GET',
    operationId: 'tech.technician-available',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/technicians/me/queue',
    method: 'GET',
    operationId: 'tech.technician-me-queue',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/template-versions/{versionId}',
    method: 'PATCH',
    operationId: 'shared.template-version-revise',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/template-versions/{versionId}/approval',
    method: 'POST',
    operationId: 'shared.template-version-approve',
    idempotent: false,
    auditClass: 'approval',
  },
  {
    template: '/template-versions/{versionId}/items',
    method: 'POST',
    operationId: 'dia.template-item-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/template-versions/{versionId}/preview',
    method: 'POST',
    operationId: 'shared.template-version-preview',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/template-versions/{versionId}/retirement',
    method: 'POST',
    operationId: 'shared.template-version-retire',
    idempotent: false,
    auditClass: 'privileged',
  },
  {
    template: '/template-versions/{versionId}/status',
    method: 'POST',
    operationId: 'dia.template-version-status-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicle-catalogue/body-types',
    method: 'GET',
    operationId: 'veh.catalogue-body-type-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-catalogue/makes',
    method: 'GET',
    operationId: 'veh.catalogue-make-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-catalogue/makes/{makeId}/models',
    method: 'GET',
    operationId: 'veh.catalogue-model-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-catalogue/models/{modelId}/trims',
    method: 'GET',
    operationId: 'veh.catalogue-trim-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-catalogue/powertrain-types',
    method: 'GET',
    operationId: 'veh.catalogue-powertrain-type-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-duplicates',
    method: 'GET',
    operationId: 'veh.vehicle-duplicate-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicle-duplicates/{candidateId}/review',
    method: 'POST',
    operationId: 'veh.vehicle-duplicate-review',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles',
    method: 'GET',
    operationId: 'veh.vehicle-search',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles',
    method: 'POST',
    operationId: 'veh.vehicle-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}',
    method: 'GET',
    operationId: 'veh.vehicle-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}',
    method: 'PATCH',
    operationId: 'veh.vehicle-update',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/authorized-parties',
    method: 'POST',
    operationId: 'veh.vehicle-authorized-party-add',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/authorized-parties/{relationshipId}/retirement',
    method: 'POST',
    operationId: 'veh.vehicle-authorized-party-retire',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/documents',
    method: 'GET',
    operationId: 'veh.vehicle-document-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/duplicate-scans',
    method: 'POST',
    operationId: 'veh.vehicle-duplicate-scan',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/ev-profile',
    method: 'GET',
    operationId: 'veh.vehicle-ev-profile-read',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/ev-profile',
    method: 'POST',
    operationId: 'veh.vehicle-ev-profile-set',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/history',
    method: 'GET',
    operationId: 'veh.vehicle-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/merge',
    method: 'POST',
    operationId: 'veh.vehicle-merge',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/odometer-readings',
    method: 'GET',
    operationId: 'veh.vehicle-odometer-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/odometer-readings',
    method: 'POST',
    operationId: 'veh.vehicle-odometer-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/ownerships',
    method: 'GET',
    operationId: 'veh.vehicle-ownership-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/ownerships',
    method: 'POST',
    operationId: 'veh.vehicle-ownership-transfer',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/plates',
    method: 'GET',
    operationId: 'veh.vehicle-plate-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/plates',
    method: 'POST',
    operationId: 'veh.vehicle-plate-assign',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/vehicles/{vehicleId}/relationships',
    method: 'GET',
    operationId: 'veh.vehicle-relationship-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/vehicles/{vehicleId}/status',
    method: 'PATCH',
    operationId: 'veh.vehicle-status-change',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/warranties/{warrantyId}',
    method: 'GET',
    operationId: 'wty.warranty-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-order-catalogue',
    method: 'GET',
    operationId: 'wo.work-order-catalogue',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders',
    method: 'GET',
    operationId: 'wo.work-order-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}',
    method: 'GET',
    operationId: 'wo.work-order-detail',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/additional-work',
    method: 'GET',
    operationId: 'wo.additional-work-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/additional-work',
    method: 'POST',
    operationId: 'wo.additional-work-request',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/closure',
    method: 'POST',
    operationId: 'wo.work-order-closure',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/closure-eligibility',
    method: 'GET',
    operationId: 'wo.work-order-closure-eligibility',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/evidence',
    method: 'GET',
    operationId: 'wo.work-order-evidence-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/history',
    method: 'GET',
    operationId: 'wo.work-order-history',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/invoice-preview',
    method: 'GET',
    operationId: 'sal.invoice-preview',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/jobs',
    method: 'POST',
    operationId: 'wo.job-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/quality-controls',
    method: 'GET',
    operationId: 'qms.qc-record-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/quality-controls',
    method: 'POST',
    operationId: 'qms.qc-record-open',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/reopen-attempts',
    method: 'GET',
    operationId: 'qms.reopen-attempt-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/reopen-attempts',
    method: 'POST',
    operationId: 'qms.reopen-attempt',
    idempotent: true,
    auditClass: 'security',
  },
  {
    template: '/work-orders/{workOrderId}/required-parts',
    method: 'GET',
    operationId: 'wo.required-part-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/required-parts',
    method: 'POST',
    operationId: 'wo.required-part-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/rework',
    method: 'GET',
    operationId: 'qms.rework-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/rework',
    method: 'POST',
    operationId: 'qms.rework-create',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/service-lines',
    method: 'GET',
    operationId: 'wo.service-line-list',
    idempotent: false,
    auditClass: 'none',
  },
  {
    template: '/work-orders/{workOrderId}/service-lines',
    method: 'POST',
    operationId: 'wo.service-line-record',
    idempotent: true,
    auditClass: 'privileged',
  },
  {
    template: '/work-orders/{workOrderId}/transition',
    method: 'POST',
    operationId: 'wo.work-order-transition',
    idempotent: true,
    auditClass: 'privileged',
  },
]);
