/**
 * GENERATED — do not edit by hand.
 *
 * Produced by `scripts/ci/generate-idempotent-operations.mjs` from the published
 * contract `docs/api/openapi.v1.json`, and reconciled against it by
 * `npm run validate:idempotent-operations`.
 *
 * ## What this is for (`P1-27-INT-003`)
 *
 * The backend requires an `Idempotency-Key` header on every operation it
 * registers as idempotent, and answers `400 ERR-INT-002` without one — before
 * authorization is evaluated. That set is NOT "the POST operations": it is
 * currently 120 operations (PATCH 3, POST 111, PUT 6).
 *
 * The client used to infer the answer from the HTTP method, which was wrong for
 * every non-POST member of that set. This table is the contract instead of a
 * guess, and the gate is what keeps it true.
 */

/** One published operation, keyed by the template the client calls. */
export interface PublishedOperation {
  /** Path template WITHOUT the `/api/v1` prefix — the client holds that. */
  readonly template: string;
  readonly method: string;
  readonly operationId: string;
  /** True when the backend will refuse the request without a key. */
  readonly idempotent: boolean;
}

/** Every operation the contract publishes. 238 of them. */
export const PUBLISHED_OPERATIONS: readonly PublishedOperation[] = Object.freeze([
  {
    template: '/additional-work/{requestId}/approval',
    method: 'GET',
    operationId: 'wo.additional-work-approval-read',
    idempotent: false,
  },
  {
    template: '/additional-work/{requestId}/approval',
    method: 'POST',
    operationId: 'wo.additional-work-approval',
    idempotent: true,
  },
  {
    template: '/additional-work/{requestId}/detail',
    method: 'GET',
    operationId: 'wo.additional-work-detail-read',
    idempotent: false,
  },
  {
    template: '/additional-work/{requestId}/detail',
    method: 'PUT',
    operationId: 'wo.additional-work-detail-record',
    idempotent: true,
  },
  {
    template: '/additional-work/{requestId}/fulfillment',
    method: 'POST',
    operationId: 'wo.additional-work-fulfillment',
    idempotent: true,
  },
  {
    template: '/additional-work/{requestId}/withdrawal',
    method: 'POST',
    operationId: 'wo.additional-work-withdraw',
    idempotent: true,
  },
  {
    template: '/appointments',
    method: 'POST',
    operationId: 'apt.appointment-create',
    idempotent: true,
  },
  {
    template: '/appointments/{appointmentId}/cancel',
    method: 'POST',
    operationId: 'apt.appointment-cancel',
    idempotent: true,
  },
  {
    template: '/appointments/{appointmentId}/no-show',
    method: 'POST',
    operationId: 'apt.appointment-no-show',
    idempotent: true,
  },
  {
    template: '/appointments/{appointmentId}/reschedule',
    method: 'POST',
    operationId: 'apt.appointment-reschedule',
    idempotent: true,
  },
  {
    template: '/assignments/{assignmentId}/end',
    method: 'POST',
    operationId: 'wo.job-assignment-end',
    idempotent: false,
  },
  {
    template: '/attachments/documents/{documentId}',
    method: 'GET',
    operationId: 'shared.document-read',
    idempotent: false,
  },
  {
    template: '/attachments/documents/{documentId}/download-authorizations',
    method: 'POST',
    operationId: 'shared.attachment-download-authorize',
    idempotent: false,
  },
  {
    template: '/attachments/documents/{documentId}/links',
    method: 'POST',
    operationId: 'shared.attachment-link-create',
    idempotent: true,
  },
  {
    template: '/attachments/documents/{documentId}/retention-evaluations',
    method: 'POST',
    operationId: 'shared.document-retention-evaluate',
    idempotent: false,
  },
  {
    template: '/attachments/links/{linkId}',
    method: 'DELETE',
    operationId: 'shared.attachment-link-withdraw',
    idempotent: false,
  },
  {
    template: '/attachments/upload-authorizations',
    method: 'POST',
    operationId: 'shared.attachment-upload-authorize',
    idempotent: true,
  },
  {
    template: '/attachments/versions',
    method: 'POST',
    operationId: 'shared.attachment-version-register',
    idempotent: true,
  },
  {
    template: '/attachments/versions/{versionId}/rejection',
    method: 'POST',
    operationId: 'shared.attachment-version-reject',
    idempotent: false,
  },
  {
    template: '/audit-events',
    method: 'GET',
    operationId: 'iam.audit-event-list',
    idempotent: false,
  },
  {
    template: '/audit-events/{recordId}',
    method: 'GET',
    operationId: 'iam.audit-event-detail',
    idempotent: false,
  },
  { template: '/auth/login', method: 'POST', operationId: 'iam.auth-login', idempotent: false },
  { template: '/auth/logout', method: 'POST', operationId: 'iam.auth-logout', idempotent: false },
  {
    template: '/auth/password-reset',
    method: 'POST',
    operationId: 'iam.auth-password-reset',
    idempotent: false,
  },
  {
    template: '/auth/password-reset/completion',
    method: 'POST',
    operationId: 'iam.auth-password-reset-completion',
    idempotent: false,
  },
  { template: '/auth/session', method: 'GET', operationId: 'iam.auth-session', idempotent: false },
  {
    template: '/credit-notes/{creditNoteId}/approval',
    method: 'POST',
    operationId: 'sal.credit-note-approve',
    idempotent: true,
  },
  {
    template: '/customer-duplicates',
    method: 'GET',
    operationId: 'crm.duplicate-list',
    idempotent: false,
  },
  {
    template: '/customer-duplicates/{candidateId}/review',
    method: 'POST',
    operationId: 'crm.duplicate-review',
    idempotent: true,
  },
  {
    template: '/customer-supplied-parts',
    method: 'POST',
    operationId: 'inv.customer-supplied-part-create',
    idempotent: true,
  },
  { template: '/customers', method: 'GET', operationId: 'crm.customer-search', idempotent: false },
  {
    template: '/customers/{customerId}',
    method: 'GET',
    operationId: 'crm.customer-read',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/addresses',
    method: 'GET',
    operationId: 'crm.address-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/addresses',
    method: 'POST',
    operationId: 'crm.address-add',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/alerts',
    method: 'GET',
    operationId: 'crm.alert-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/alerts',
    method: 'POST',
    operationId: 'crm.alert-raise',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/consents',
    method: 'GET',
    operationId: 'crm.consent-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/consents',
    method: 'POST',
    operationId: 'crm.consent-record',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/contacts',
    method: 'GET',
    operationId: 'crm.contact-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/contacts',
    method: 'POST',
    operationId: 'crm.contact-add',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/duplicate-scans',
    method: 'POST',
    operationId: 'crm.duplicate-scan',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/history',
    method: 'GET',
    operationId: 'crm.customer-history',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/merge',
    method: 'POST',
    operationId: 'crm.customer-merge',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/notes',
    method: 'GET',
    operationId: 'crm.note-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/notes',
    method: 'POST',
    operationId: 'crm.note-add',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/preferences',
    method: 'GET',
    operationId: 'crm.preference-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/preferences',
    method: 'PUT',
    operationId: 'crm.preference-set',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/restrictions',
    method: 'GET',
    operationId: 'crm.restriction-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/restrictions',
    method: 'POST',
    operationId: 'crm.restriction-impose',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/status',
    method: 'PUT',
    operationId: 'crm.customer-status-set',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/tags',
    method: 'GET',
    operationId: 'crm.tag-list',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/tags',
    method: 'POST',
    operationId: 'crm.tag-assign',
    idempotent: true,
  },
  {
    template: '/customers/{customerId}/timeline',
    method: 'GET',
    operationId: 'crm.customer-timeline',
    idempotent: false,
  },
  {
    template: '/customers/{customerId}/vehicles',
    method: 'POST',
    operationId: 'crm.vehicle-link',
    idempotent: true,
  },
  {
    template: '/customers/companies',
    method: 'POST',
    operationId: 'crm.company-create',
    idempotent: true,
  },
  {
    template: '/customers/individuals',
    method: 'POST',
    operationId: 'crm.individual-create',
    idempotent: true,
  },
  {
    template: '/damaged-stock',
    method: 'POST',
    operationId: 'inv.damaged-stock-create',
    idempotent: true,
  },
  { template: '/deliveries', method: 'POST', operationId: 'sal.delivery-create', idempotent: true },
  {
    template: '/deliveries/{deliveryId}/authorized-receiver',
    method: 'POST',
    operationId: 'sal.delivery-receiver-verify',
    idempotent: true,
  },
  {
    template: '/deliveries/{deliveryId}/checklist-results',
    method: 'POST',
    operationId: 'sal.delivery-checklist-record',
    idempotent: true,
  },
  {
    template: '/deliveries/{deliveryId}/completion',
    method: 'POST',
    operationId: 'sal.delivery-complete',
    idempotent: true,
  },
  {
    template: '/deliveries/{deliveryId}/eligibility',
    method: 'GET',
    operationId: 'sal.delivery-eligibility-read',
    idempotent: false,
  },
  {
    template: '/deliveries/{deliveryId}/signatures',
    method: 'POST',
    operationId: 'sal.delivery-signature-attach',
    idempotent: true,
  },
  {
    template: '/deliveries/{deliveryId}/warranties',
    method: 'POST',
    operationId: 'wty.warranty-generate',
    idempotent: true,
  },
  {
    template: '/exports/authorizations',
    method: 'POST',
    operationId: 'shared.export-authorize',
    idempotent: false,
  },
  {
    template: '/exports/resources',
    method: 'GET',
    operationId: 'shared.export-catalogue',
    idempotent: false,
  },
  {
    template: '/external-purchase-parts',
    method: 'POST',
    operationId: 'inv.external-purchase-part-create',
    idempotent: true,
  },
  { template: '/health/live', method: 'GET', operationId: 'shared.health-live', idempotent: false },
  {
    template: '/health/ready',
    method: 'GET',
    operationId: 'shared.health-ready',
    idempotent: false,
  },
  {
    template: '/iam/approval-limits',
    method: 'GET',
    operationId: 'iam.approval-limit-list',
    idempotent: false,
  },
  {
    template: '/iam/approval-limits',
    method: 'POST',
    operationId: 'iam.approval-limit-create',
    idempotent: true,
  },
  {
    template: '/iam/approval-limits/{limitId}',
    method: 'PATCH',
    operationId: 'iam.approval-limit-end',
    idempotent: false,
  },
  { template: '/iam/grants', method: 'POST', operationId: 'iam.grant-issue', idempotent: true },
  {
    template: '/iam/grants/{grantId}',
    method: 'DELETE',
    operationId: 'iam.grant-revoke',
    idempotent: false,
  },
  {
    template: '/iam/grants/{grantId}/scopes',
    method: 'GET',
    operationId: 'iam.grant-scope-list',
    idempotent: false,
  },
  {
    template: '/iam/grants/{grantId}/scopes',
    method: 'POST',
    operationId: 'iam.grant-scope-add',
    idempotent: true,
  },
  {
    template: '/iam/grants/{grantId}/scopes/{scopeId}',
    method: 'DELETE',
    operationId: 'iam.grant-scope-remove',
    idempotent: false,
  },
  {
    template: '/iam/invitations',
    method: 'POST',
    operationId: 'iam.invitation-create',
    idempotent: true,
  },
  {
    template: '/iam/invitations/{userId}',
    method: 'DELETE',
    operationId: 'iam.invitation-cancel',
    idempotent: false,
  },
  {
    template: '/iam/invitations/{userId}/activation',
    method: 'POST',
    operationId: 'iam.invitation-activate',
    idempotent: true,
  },
  {
    template: '/iam/permissions',
    method: 'GET',
    operationId: 'iam.permission-list',
    idempotent: false,
  },
  { template: '/iam/roles', method: 'GET', operationId: 'iam.role-list', idempotent: false },
  { template: '/iam/roles', method: 'POST', operationId: 'iam.role-create', idempotent: true },
  {
    template: '/iam/roles/{roleId}',
    method: 'PATCH',
    operationId: 'iam.role-update',
    idempotent: false,
  },
  {
    template: '/iam/roles/{roleId}/permissions',
    method: 'GET',
    operationId: 'iam.role-permission-list',
    idempotent: false,
  },
  {
    template: '/iam/roles/{roleId}/permissions',
    method: 'POST',
    operationId: 'iam.role-permission-add',
    idempotent: true,
  },
  {
    template: '/iam/roles/{roleId}/permissions/{mappingId}',
    method: 'DELETE',
    operationId: 'iam.role-permission-remove',
    idempotent: false,
  },
  {
    template: '/iam/roles/{roleId}/permissions/{mappingId}',
    method: 'PATCH',
    operationId: 'iam.role-permission-update',
    idempotent: false,
  },
  { template: '/iam/users', method: 'GET', operationId: 'iam.user-list', idempotent: false },
  {
    template: '/iam/users/{userId}',
    method: 'GET',
    operationId: 'iam.user-detail',
    idempotent: false,
  },
  {
    template: '/iam/users/{userId}',
    method: 'PATCH',
    operationId: 'iam.user-update',
    idempotent: false,
  },
  {
    template: '/iam/users/{userId}/sessions',
    method: 'DELETE',
    operationId: 'iam.user-session-revoke-all',
    idempotent: false,
  },
  {
    template: '/iam/users/{userId}/sessions',
    method: 'GET',
    operationId: 'iam.user-session-list',
    idempotent: false,
  },
  {
    template: '/iam/users/{userId}/status',
    method: 'POST',
    operationId: 'iam.user-status-change',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}',
    method: 'GET',
    operationId: 'dia.diagnostic-detail',
    idempotent: false,
  },
  {
    template: '/inspections/{inspectionId}/completion',
    method: 'POST',
    operationId: 'dia.diagnostic-complete',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/dtcs',
    method: 'POST',
    operationId: 'dia.diagnostic-dtc-record',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/evidence',
    method: 'POST',
    operationId: 'dia.diagnostic-evidence-record',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/findings',
    method: 'POST',
    operationId: 'dia.diagnostic-finding-record',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/history',
    method: 'GET',
    operationId: 'dia.diagnostic-history',
    idempotent: false,
  },
  {
    template: '/inspections/{inspectionId}/items/{templateItemId}',
    method: 'PUT',
    operationId: 'dia.diagnostic-item-result',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/measurements',
    method: 'POST',
    operationId: 'dia.diagnostic-measurement-record',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/recommendations',
    method: 'POST',
    operationId: 'dia.diagnostic-recommendation-record',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/reviews',
    method: 'POST',
    operationId: 'dia.diagnostic-review',
    idempotent: true,
  },
  {
    template: '/inspections/{inspectionId}/transition',
    method: 'POST',
    operationId: 'dia.diagnostic-transition',
    idempotent: true,
  },
  {
    template: '/inventory-reconciliations',
    method: 'GET',
    operationId: 'inv.inventory-reconciliation-read',
    idempotent: false,
  },
  { template: '/invoices', method: 'POST', operationId: 'sal.invoice-create', idempotent: true },
  {
    template: '/invoices/{invoiceId}',
    method: 'GET',
    operationId: 'sal.invoice-detail',
    idempotent: false,
  },
  {
    template: '/invoices/{invoiceId}/cancellation',
    method: 'POST',
    operationId: 'sal.invoice-cancel',
    idempotent: true,
  },
  {
    template: '/invoices/{invoiceId}/credit-notes',
    method: 'POST',
    operationId: 'sal.credit-note-create',
    idempotent: true,
  },
  {
    template: '/invoices/{invoiceId}/issuance',
    method: 'POST',
    operationId: 'sal.invoice-issue',
    idempotent: true,
  },
  {
    template: '/invoices/{invoiceId}/outstanding',
    method: 'GET',
    operationId: 'sal.invoice-outstanding-read',
    idempotent: false,
  },
  { template: '/items', method: 'GET', operationId: 'inv.item-search', idempotent: false },
  { template: '/jobs/{jobId}', method: 'PATCH', operationId: 'wo.job-update', idempotent: false },
  {
    template: '/jobs/{jobId}/assignments',
    method: 'GET',
    operationId: 'wo.job-assignment-list',
    idempotent: false,
  },
  {
    template: '/jobs/{jobId}/assignments',
    method: 'POST',
    operationId: 'wo.job-assignment-create',
    idempotent: true,
  },
  {
    template: '/jobs/{jobId}/history',
    method: 'GET',
    operationId: 'wo.job-history',
    idempotent: false,
  },
  {
    template: '/jobs/{jobId}/inspections',
    method: 'GET',
    operationId: 'dia.diagnostic-list',
    idempotent: false,
  },
  {
    template: '/jobs/{jobId}/inspections',
    method: 'POST',
    operationId: 'dia.diagnostic-create',
    idempotent: true,
  },
  {
    template: '/jobs/{jobId}/labor-sessions',
    method: 'GET',
    operationId: 'tech.labor-session-list',
    idempotent: false,
  },
  {
    template: '/jobs/{jobId}/labor-sessions',
    method: 'POST',
    operationId: 'tech.labor-session-start',
    idempotent: true,
  },
  {
    template: '/jobs/{jobId}/reassignments',
    method: 'POST',
    operationId: 'wo.job-reassignment',
    idempotent: true,
  },
  {
    template: '/jobs/{jobId}/transition',
    method: 'POST',
    operationId: 'wo.job-transition',
    idempotent: true,
  },
  {
    template: '/labor-sessions/{sessionId}/corrections',
    method: 'POST',
    operationId: 'tech.labor-session-correct',
    idempotent: false,
  },
  {
    template: '/labor-sessions/{sessionId}/stop',
    method: 'POST',
    operationId: 'tech.labor-session-stop',
    idempotent: false,
  },
  {
    template: '/message-templates',
    method: 'POST',
    operationId: 'shared.template-create',
    idempotent: true,
  },
  {
    template: '/message-templates/{templateId}',
    method: 'PATCH',
    operationId: 'shared.template-update',
    idempotent: false,
  },
  {
    template: '/message-templates/{templateId}/active-version',
    method: 'PUT',
    operationId: 'shared.template-activation-set',
    idempotent: false,
  },
  {
    template: '/message-templates/{templateId}/versions',
    method: 'POST',
    operationId: 'shared.template-version-create',
    idempotent: true,
  },
  { template: '/meta/ping', method: 'GET', operationId: 'meta.ping', idempotent: false },
  {
    template: '/notifications',
    method: 'GET',
    operationId: 'shared.notification-list',
    idempotent: false,
  },
  {
    template: '/notifications',
    method: 'POST',
    operationId: 'shared.notification-enqueue',
    idempotent: true,
  },
  {
    template: '/notifications/{notificationId}',
    method: 'GET',
    operationId: 'shared.notification-read',
    idempotent: false,
  },
  {
    template: '/notifications/{notificationId}/deliveries',
    method: 'GET',
    operationId: 'shared.notification-delivery-list',
    idempotent: false,
  },
  {
    template: '/opening-inventory-batches',
    method: 'POST',
    operationId: 'inv.opening-batch-create',
    idempotent: true,
  },
  {
    template: '/opening-inventory-batches/{batchId}/approval',
    method: 'POST',
    operationId: 'inv.opening-batch-approve',
    idempotent: true,
  },
  {
    template: '/opening-inventory-batches/{batchId}/lines',
    method: 'POST',
    operationId: 'inv.opening-batch-line-create',
    idempotent: false,
  },
  {
    template: '/org/branches/{branchId}/settings',
    method: 'GET',
    operationId: 'iam.branch-settings-read',
    idempotent: false,
  },
  {
    template: '/org/branches/{branchId}/settings',
    method: 'POST',
    operationId: 'iam.branch-settings-write',
    idempotent: true,
  },
  {
    template: '/org/companies/{companyId}/settings',
    method: 'GET',
    operationId: 'iam.company-settings-read',
    idempotent: false,
  },
  {
    template: '/org/companies/{companyId}/settings',
    method: 'POST',
    operationId: 'iam.company-settings-write',
    idempotent: true,
  },
  {
    template: '/org/tenant',
    method: 'GET',
    operationId: 'iam.tenant-settings-read',
    idempotent: false,
  },
  {
    template: '/org/tenant',
    method: 'PATCH',
    operationId: 'iam.tenant-settings-update',
    idempotent: false,
  },
  {
    template: '/organization/branches/{branchId}/status',
    method: 'GET',
    operationId: 'shared.branch-status-read',
    idempotent: false,
  },
  {
    template: '/organization/branches/{branchId}/status',
    method: 'POST',
    operationId: 'shared.branch-status-change',
    idempotent: false,
  },
  {
    template: '/payment-methods',
    method: 'GET',
    operationId: 'sal.payment-method-list',
    idempotent: false,
  },
  { template: '/payments', method: 'POST', operationId: 'sal.payment-record', idempotent: true },
  {
    template: '/payments/{paymentId}',
    method: 'GET',
    operationId: 'sal.receipt-detail',
    idempotent: false,
  },
  {
    template: '/payments/{paymentId}/allocations',
    method: 'POST',
    operationId: 'sal.payment-allocate',
    idempotent: true,
  },
  {
    template: '/price-lists',
    method: 'GET',
    operationId: 'svc.price-list-list',
    idempotent: false,
  },
  {
    template: '/price-lists',
    method: 'POST',
    operationId: 'svc.price-list-create',
    idempotent: true,
  },
  {
    template: '/price-lists/{priceListId}/versions',
    method: 'POST',
    operationId: 'svc.price-list-version-create',
    idempotent: true,
  },
  {
    template: '/price-lists/{priceListId}/versions/{versionId}/publication',
    method: 'POST',
    operationId: 'svc.price-list-version-publish',
    idempotent: true,
  },
  {
    template: '/price-lists/{priceListId}/versions/{versionId}/rules',
    method: 'POST',
    operationId: 'svc.price-rule-record',
    idempotent: true,
  },
  { template: '/prices', method: 'GET', operationId: 'svc.price-resolve', idempotent: false },
  {
    template: '/quality-controls/{recordId}',
    method: 'GET',
    operationId: 'qms.qc-record-detail',
    idempotent: false,
  },
  {
    template: '/quality-controls/{recordId}/checks/{qcCheckId}',
    method: 'PUT',
    operationId: 'qms.qc-check-result',
    idempotent: true,
  },
  {
    template: '/quality-controls/{recordId}/finalization',
    method: 'POST',
    operationId: 'qms.qc-record-finalize',
    idempotent: true,
  },
  {
    template: '/quotation-items/{quotationItemId}/decisions',
    method: 'POST',
    operationId: 'quo.quotation-item-decide',
    idempotent: true,
  },
  {
    template: '/quotation-revisions/{revisionId}/decisions',
    method: 'POST',
    operationId: 'quo.quotation-revision-decide',
    idempotent: true,
  },
  {
    template: '/quotations',
    method: 'POST',
    operationId: 'quo.quotation-create',
    idempotent: true,
  },
  {
    template: '/quotations/{quotationId}',
    method: 'GET',
    operationId: 'quo.quotation-detail',
    idempotent: false,
  },
  {
    template: '/quotations/{quotationId}/issue',
    method: 'POST',
    operationId: 'quo.quotation-issue',
    idempotent: true,
  },
  {
    template: '/quotations/{quotationId}/revisions',
    method: 'POST',
    operationId: 'quo.quotation-revision-create',
    idempotent: true,
  },
  {
    template: '/receptions',
    method: 'POST',
    operationId: 'rec.reception-create',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/approve',
    method: 'POST',
    operationId: 'rec.reception-approve',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/authorizations',
    method: 'POST',
    operationId: 'rec.reception-authorization',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/condition-evidence',
    method: 'POST',
    operationId: 'rec.reception-condition-evidence',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/convert-to-work-order',
    method: 'POST',
    operationId: 'rec.reception-convert-to-work-order',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/party-roles',
    method: 'POST',
    operationId: 'rec.reception-party-role',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/refusals',
    method: 'POST',
    operationId: 'rec.reception-refusal',
    idempotent: true,
  },
  {
    template: '/receptions/{receptionId}/signatures',
    method: 'POST',
    operationId: 'rec.reception-signature',
    idempotent: true,
  },
  { template: '/reports', method: 'GET', operationId: 'rpt.report-catalogue', idempotent: false },
  {
    template: '/reports/{reportCode}',
    method: 'GET',
    operationId: 'rpt.report-read',
    idempotent: false,
  },
  {
    template: '/rework-links/{reworkLinkId}',
    method: 'GET',
    operationId: 'qms.rework-detail',
    idempotent: false,
  },
  {
    template: '/rework-links/{reworkLinkId}/cost',
    method: 'GET',
    operationId: 'qms.rework-cost-read',
    idempotent: false,
  },
  {
    template: '/rework-links/{reworkLinkId}/cost',
    method: 'PUT',
    operationId: 'qms.rework-cost-record',
    idempotent: true,
  },
  {
    template: '/rework-links/{reworkLinkId}/sign-off',
    method: 'POST',
    operationId: 'qms.rework-sign-off',
    idempotent: true,
  },
  { template: '/services', method: 'GET', operationId: 'svc.service-list', idempotent: false },
  { template: '/services', method: 'POST', operationId: 'svc.service-create', idempotent: true },
  {
    template: '/services/{serviceId}',
    method: 'PATCH',
    operationId: 'svc.service-update',
    idempotent: true,
  },
  {
    template: '/services/{serviceId}/branch-availability',
    method: 'POST',
    operationId: 'svc.branch-availability-set',
    idempotent: true,
  },
  {
    template: '/services/{serviceId}/versions/{versionId}/publication',
    method: 'POST',
    operationId: 'svc.service-version-publish',
    idempotent: true,
  },
  {
    template: '/stock-availability',
    method: 'GET',
    operationId: 'inv.stock-availability-read',
    idempotent: false,
  },
  {
    template: '/stock-issues',
    method: 'POST',
    operationId: 'inv.stock-issue-create',
    idempotent: true,
  },
  {
    template: '/stock-movements',
    method: 'GET',
    operationId: 'inv.stock-movement-list',
    idempotent: false,
  },
  {
    template: '/stock-reservations',
    method: 'POST',
    operationId: 'inv.stock-reservation-create',
    idempotent: true,
  },
  {
    template: '/stock-reservations/{reservationId}/release',
    method: 'POST',
    operationId: 'inv.stock-reservation-release',
    idempotent: false,
  },
  {
    template: '/stock-returns',
    method: 'POST',
    operationId: 'inv.stock-return-create',
    idempotent: true,
  },
  {
    template: '/technicians/{technicianProfileId}/queue',
    method: 'GET',
    operationId: 'tech.technician-queue',
    idempotent: false,
  },
  {
    template: '/technicians/available',
    method: 'GET',
    operationId: 'tech.technician-available',
    idempotent: false,
  },
  {
    template: '/template-versions/{versionId}',
    method: 'PATCH',
    operationId: 'shared.template-version-revise',
    idempotent: false,
  },
  {
    template: '/template-versions/{versionId}/approval',
    method: 'POST',
    operationId: 'shared.template-version-approve',
    idempotent: false,
  },
  {
    template: '/template-versions/{versionId}/preview',
    method: 'POST',
    operationId: 'shared.template-version-preview',
    idempotent: false,
  },
  {
    template: '/template-versions/{versionId}/retirement',
    method: 'POST',
    operationId: 'shared.template-version-retire',
    idempotent: false,
  },
  {
    template: '/vehicle-duplicates',
    method: 'GET',
    operationId: 'veh.vehicle-duplicate-list',
    idempotent: false,
  },
  {
    template: '/vehicle-duplicates/{candidateId}/review',
    method: 'POST',
    operationId: 'veh.vehicle-duplicate-review',
    idempotent: true,
  },
  { template: '/vehicles', method: 'GET', operationId: 'veh.vehicle-search', idempotent: false },
  { template: '/vehicles', method: 'POST', operationId: 'veh.vehicle-create', idempotent: true },
  {
    template: '/vehicles/{vehicleId}',
    method: 'GET',
    operationId: 'veh.vehicle-read',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}',
    method: 'PATCH',
    operationId: 'veh.vehicle-update',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/authorized-parties',
    method: 'POST',
    operationId: 'veh.vehicle-authorized-party-add',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/authorized-parties/{relationshipId}/retirement',
    method: 'POST',
    operationId: 'veh.vehicle-authorized-party-retire',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/documents',
    method: 'GET',
    operationId: 'veh.vehicle-document-list',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/duplicate-scans',
    method: 'POST',
    operationId: 'veh.vehicle-duplicate-scan',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/ev-profile',
    method: 'GET',
    operationId: 'veh.vehicle-ev-profile-read',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/ev-profile',
    method: 'POST',
    operationId: 'veh.vehicle-ev-profile-set',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/history',
    method: 'GET',
    operationId: 'veh.vehicle-history',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/merge',
    method: 'POST',
    operationId: 'veh.vehicle-merge',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/odometer-readings',
    method: 'GET',
    operationId: 'veh.vehicle-odometer-history',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/odometer-readings',
    method: 'POST',
    operationId: 'veh.vehicle-odometer-record',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/ownerships',
    method: 'GET',
    operationId: 'veh.vehicle-ownership-history',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/ownerships',
    method: 'POST',
    operationId: 'veh.vehicle-ownership-transfer',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/plates',
    method: 'GET',
    operationId: 'veh.vehicle-plate-history',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/plates',
    method: 'POST',
    operationId: 'veh.vehicle-plate-assign',
    idempotent: true,
  },
  {
    template: '/vehicles/{vehicleId}/relationships',
    method: 'GET',
    operationId: 'veh.vehicle-relationship-list',
    idempotent: false,
  },
  {
    template: '/vehicles/{vehicleId}/status',
    method: 'PATCH',
    operationId: 'veh.vehicle-status-change',
    idempotent: true,
  },
  {
    template: '/warranties/{warrantyId}',
    method: 'GET',
    operationId: 'wty.warranty-detail',
    idempotent: false,
  },
  { template: '/work-orders', method: 'GET', operationId: 'wo.work-order-list', idempotent: false },
  {
    template: '/work-orders/{workOrderId}',
    method: 'GET',
    operationId: 'wo.work-order-detail',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/additional-work',
    method: 'GET',
    operationId: 'wo.additional-work-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/additional-work',
    method: 'POST',
    operationId: 'wo.additional-work-request',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/closure',
    method: 'POST',
    operationId: 'wo.work-order-closure',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/closure-eligibility',
    method: 'GET',
    operationId: 'wo.work-order-closure-eligibility',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/history',
    method: 'GET',
    operationId: 'wo.work-order-history',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/invoice-preview',
    method: 'GET',
    operationId: 'sal.invoice-preview',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/jobs',
    method: 'POST',
    operationId: 'wo.job-create',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/quality-controls',
    method: 'GET',
    operationId: 'qms.qc-record-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/quality-controls',
    method: 'POST',
    operationId: 'qms.qc-record-open',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/reopen-attempts',
    method: 'GET',
    operationId: 'qms.reopen-attempt-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/reopen-attempts',
    method: 'POST',
    operationId: 'qms.reopen-attempt',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/required-parts',
    method: 'GET',
    operationId: 'wo.required-part-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/required-parts',
    method: 'POST',
    operationId: 'wo.required-part-record',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/rework',
    method: 'GET',
    operationId: 'qms.rework-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/rework',
    method: 'POST',
    operationId: 'qms.rework-create',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/service-lines',
    method: 'GET',
    operationId: 'wo.service-line-list',
    idempotent: false,
  },
  {
    template: '/work-orders/{workOrderId}/service-lines',
    method: 'POST',
    operationId: 'wo.service-line-record',
    idempotent: true,
  },
  {
    template: '/work-orders/{workOrderId}/transition',
    method: 'POST',
    operationId: 'wo.work-order-transition',
    idempotent: true,
  },
]);
