/**
 * Item barcodes and packaging identifiers (P1-32-PRE-100…104).
 *
 * An item's SKU is the identity the ledger keys on; an identifier is what a person
 * can SCAN. One item may carry any number of them — a manufacturer GTIN on the
 * unit, a second on the case with a pack quantity of twelve, a supplier's own code,
 * and an internal code printed by the workshop for an item that arrived with none.
 *
 * ## Where the guarantees live
 *
 * In the database. `normalized_value` is GENERATED by
 * `inv.normalize_item_identifier`, retail check digits are a CHECK
 * (`ck_item_identifiers_check_digit`), a live code is unique per (tenant, kind,
 * value), and the internal counter is allocated under a per-tenant advisory lock.
 * This service adds only what those objects cannot say readably: which field a
 * refusal is about, and who may act.
 *
 * ## Who may write
 *
 * `inv.item_master` has no company or branch column, so an identifier — which
 * resolves the same item in every branch — is tenant-wide reference data. Every
 * write therefore requires `inv.item.manage` granted TENANT-WIDE, exactly as
 * creating the item does (P1-18-A-01): a grant scoped to one branch must not be
 * able to redirect a scan in every other branch.
 *
 * ## What a scan resolves to
 *
 * The ITEM, never a unit — whether or not the item is serialised. No serial-unit
 * table exists. A scanned value that is live under more than one item is refused
 * as ambiguous rather than resolved to either, because choosing would put the
 * wrong part on a customer's bill in exactly the case the operator cannot see.
 *
 * ## Duplicate frames
 *
 * A scanner can deliver one physical scan twice. Every write a scan triggers is an
 * idempotent operation, and the client derives its `Idempotency-Key` ONCE per user
 * confirmation, so a doubled frame replays the first write instead of repeating it.
 *
 * ## What the label does not carry
 *
 * A price. `inv.item_sale_prices` does hold one since P1-32, but a price is
 * narrowed to a company and a branch while this operation — like the item and its
 * identifiers — is tenant-wide and takes no branch. There is therefore no single
 * figure a label could print, whatever permission the caller holds; a screen that
 * prints a shelf label for ONE branch reads that branch's price through
 * `GET /items/{itemId}/sale-prices`.
 */
import { AppFailure } from '@/server/errors/app-failure';
import { appendAudit } from '@/server/audit/audit';
import { isSqlState, SQLSTATE } from '@/server/db/repository';
import {
  callerHoldsPermission,
  callerHoldsPermissionTenantWide,
  type ScopeAuthorizer,
} from '@/server/auth/authorization';
import type { DbHandle } from '@/server/db/transaction';
import type { Page } from '@/server/db/pagination';
import type {
  InventoryRepository,
  ItemIdentifierRow,
  ItemRow,
  ResolvedIdentifierRow,
} from '../data/inventory-repository';
import { IDENTIFIER_KINDS, barcodeSymbologyFor, type BarcodeSymbology } from '../domain/inventory';
import { parseQuantity } from './inventory-failures';
import type { AvailabilityView, InventoryReadService } from './inventory-read-service';

/** The permission every identifier write requires, tenant-wide. */
const MANAGE_PERMISSION = 'inv.item.manage';
/** The permission a scan needs before it may also report stock at a branch. */
const STOCK_READ_PERMISSION = 'inv.stock.read';

export interface ItemIdentifierView {
  readonly id: string;
  readonly itemId: string;
  readonly kind: string;
  /** As entered. */
  readonly value: string;
  /** What a scan is matched against. */
  readonly normalizedValue: string;
  readonly unit: { readonly id: string; readonly code: string };
  /** Exact decimal string: base units one scan of this code represents. */
  readonly packQuantity: string;
  readonly isPrimary: boolean;
  readonly symbology: BarcodeSymbology;
  readonly retired: boolean;
  readonly retiredAt: string | null;
  readonly recordVersion: number;
  readonly createdAt: string;
}

export interface ItemIdentifierListView {
  readonly itemId: string;
  readonly sku: string;
  /** True when the item is serialised. A scan still resolves to the item. */
  readonly isSerialized: boolean;
  readonly identifiers: readonly ItemIdentifierView[];
}

export interface ItemIdentifierWriteView extends ItemIdentifierView {
  /** True when nothing changed because the write had already happened. */
  readonly replayed: boolean;
}

export interface BarcodeResolutionView {
  readonly scannedValue: string;
  readonly normalizedValue: string;
  readonly item: {
    readonly id: string;
    readonly sku: string;
    readonly name: string;
    readonly isSerialized: boolean;
    readonly isStockTracked: boolean;
    readonly lifecycleStatus: string;
  };
  readonly identifier: {
    readonly id: string;
    readonly kind: string;
    readonly isPrimary: boolean;
    readonly symbology: BarcodeSymbology;
  };
  readonly unit: { readonly id: string; readonly code: string };
  readonly packQuantity: string;
  /**
   * Stock of the item at the named branch, or `null` when no branch was named.
   * Present only for a caller holding `inv.stock.read` at that branch.
   */
  readonly availability: readonly AvailabilityView[] | null;
}

export interface ItemLabelView {
  readonly itemId: string;
  readonly sku: string;
  readonly name: string;
  /** `null` when the item carries no live identifier to print. */
  readonly primaryBarcode: {
    readonly identifierId: string;
    readonly kind: string;
    readonly value: string;
    readonly normalizedValue: string;
    readonly symbology: BarcodeSymbology;
  } | null;
  readonly unit: { readonly id: string; readonly code: string };
  readonly packQuantity: string;
}

const iso = (value: Date | null): string | null => (value ? value.toISOString() : null);

function toIdentifierView(row: ItemIdentifierRow): ItemIdentifierView {
  return {
    id: row.id,
    itemId: row.itemId,
    kind: row.kind,
    value: row.value,
    normalizedValue: row.normalizedValue,
    unit: { id: row.unitId, code: row.unitCode },
    packQuantity: row.packQuantity,
    isPrimary: row.isPrimary,
    symbology: barcodeSymbologyFor(row.kind, row.normalizedValue),
    retired: row.retiredAt !== null,
    retiredAt: iso(row.retiredAt),
    recordVersion: row.recordVersion,
    createdAt: row.createdAt.toISOString(),
  };
}

/** Kind precedence, then primary first — the one order every "which code" answer uses. */
function preferred<T extends ItemIdentifierRow>(rows: readonly T[]): T | null {
  const rank = (kind: string): number => {
    const index = (IDENTIFIER_KINDS as readonly string[]).indexOf(kind);
    return index === -1 ? IDENTIFIER_KINDS.length : index;
  };
  const sorted = [...rows].sort((a, b) => {
    if (a.isPrimary !== b.isPrimary) return a.isPrimary ? -1 : 1;
    return rank(a.kind) - rank(b.kind);
  });
  return sorted[0] ?? null;
}

export class InventoryIdentifierService {
  public constructor(
    private readonly repository: InventoryRepository,
    private readonly reads: InventoryReadService
  ) {}

  /** Every identifier of one item; retired ones only when asked for. */
  public async list(
    db: DbHandle,
    itemId: string,
    options: { readonly includeRetired: boolean }
  ): Promise<ItemIdentifierListView> {
    const item = await this.requireItem(db, itemId);
    const rows = await this.repository.listItemIdentifiers(db, itemId, options);
    return {
      itemId: item.id,
      sku: item.sku,
      isSerialized: item.isSerialized,
      identifiers: rows.map(toIdentifierView),
    };
  }

  /** Attaches a user-entered identifier to an item. */
  public async add(
    db: DbHandle,
    itemId: string,
    input: {
      readonly kind: string;
      readonly value: string;
      readonly unitId?: string | undefined;
      readonly packQuantity?: string | undefined;
      readonly isPrimary?: boolean | undefined;
    }
  ): Promise<ItemIdentifierWriteView> {
    await this.requireTenantWideManage(db);
    const item = await this.requireItem(db, itemId);
    if (item.lifecycleStatus !== 'active') {
      throw new AppFailure('ERR-TRN-001', {
        message: `Item ${item.sku} is ${item.lifecycleStatus} and takes no new identifier`,
      });
    }
    if (input.unitId !== undefined) {
      const unit = await this.repository.readUnitOfMeasure(db, input.unitId);
      if (unit === null) {
        refuse('body.unitId', 'unknown_unit', `Unit of measure ${input.unitId} is not visible`);
      }
      if (unit.status !== 'active') {
        refuse('body.unitId', 'inactive_unit', `Unit of measure ${unit.code} is ${unit.status}`);
      }
    }
    const packQuantity = parseQuantity(input.packQuantity ?? '1', 'packQuantity');

    let identifierId: string;
    try {
      identifierId = await this.repository.addItemIdentifier(db, {
        itemId,
        kind: input.kind,
        value: input.value,
        unitId: input.unitId ?? null,
        packQuantity: packQuantity.toString(),
        isPrimary: input.isPrimary ?? false,
      });
    } catch (cause) {
      if (isSqlState(cause, SQLSTATE.uniqueViolation)) {
        throw new AppFailure('ERR-CON-001', {
          message: 'This code is already registered as a live identifier of that kind',
          safeDetails: { violations: [{ path: 'body.value', rule: 'duplicate_identifier' }] },
        });
      }
      if (isSqlState(cause, SQLSTATE.checkViolation)) {
        // The item's state and the unit were checked above, so what remains is the
        // value itself: a retail code with a wrong check digit or length.
        refuse(
          'body.value',
          'invalid_identifier',
          'The code is not valid for its kind. A GTIN, EAN or UPC must have the right ' +
            'number of digits and a correct check digit.'
        );
      }
      throw cause;
    }

    const created = await this.requireIdentifier(db, identifierId);
    await appendAudit(db, {
      action: 'inv.item_identifier.added',
      entityType: 'inv.item_identifier',
      entityId: created.id,
      requestRef: 'inv.item-identifier-add',
      details: [
        { field: 'itemId', classification: 'internal', value: created.itemId },
        { field: 'kind', classification: 'internal', value: created.kind },
        { field: 'normalizedValue', classification: 'internal', value: created.normalizedValue },
        { field: 'packQuantity', classification: 'internal', value: created.packQuantity },
        { field: 'isPrimary', classification: 'internal', value: String(created.isPrimary) },
      ],
    });
    return { ...toIdentifierView(created), replayed: false };
  }

  /** Retires an identifier. Idempotent on an identifier that is already retired. */
  public async retire(
    db: DbHandle,
    itemId: string,
    identifierId: string
  ): Promise<ItemIdentifierWriteView> {
    await this.requireTenantWideManage(db);
    const before = await this.repository.readItemIdentifier(db, identifierId);
    if (before === null || before.itemId !== itemId) {
      throw new AppFailure('ERR-RES-001', {
        message: `Identifier ${identifierId} was not found on item ${itemId}`,
      });
    }
    if (before.retiredAt !== null) {
      return { ...toIdentifierView(before), replayed: true };
    }
    try {
      await this.repository.retireItemIdentifier(db, identifierId);
    } catch (cause) {
      if (isSqlState(cause, SQLSTATE.checkViolation)) {
        throw new AppFailure('ERR-TRN-001', {
          message: `Identifier ${identifierId} could not be retired in its current state`,
        });
      }
      throw cause;
    }
    const after = await this.requireIdentifier(db, identifierId);
    await appendAudit(db, {
      action: 'inv.item_identifier.retired',
      entityType: 'inv.item_identifier',
      entityId: after.id,
      requestRef: 'inv.item-identifier-retire',
      details: [
        { field: 'itemId', classification: 'internal', value: after.itemId },
        { field: 'kind', classification: 'internal', value: after.kind },
        { field: 'normalizedValue', classification: 'internal', value: after.normalizedValue },
      ],
    });
    return { ...toIdentifierView(after), replayed: false };
  }

  /**
   * Allocates the item's internal barcode, once.
   *
   * The existing code is detected BEFORE the call, because `inv.assign_internal_barcode`
   * returns it silently, and from the outside that is indistinguishable from a fresh
   * allocation — which would write a second audit record for one code.
   */
  public async assignInternal(db: DbHandle, itemId: string): Promise<ItemIdentifierWriteView> {
    await this.requireTenantWideManage(db);
    const item = await this.requireItem(db, itemId);
    const existing = (
      await this.repository.listItemIdentifiers(db, itemId, { includeRetired: false })
    ).find((row) => row.kind === 'internal');
    if (existing) {
      return { ...toIdentifierView(existing), replayed: true };
    }
    if (item.lifecycleStatus !== 'active') {
      throw new AppFailure('ERR-TRN-001', {
        message: `Item ${item.sku} is ${item.lifecycleStatus} and takes no new identifier`,
      });
    }

    let identifierId: string;
    try {
      identifierId = await this.repository.assignInternalBarcode(db, itemId);
    } catch (cause) {
      if (isSqlState(cause, SQLSTATE.checkViolation)) {
        throw new AppFailure('ERR-TRN-001', {
          message: 'An internal barcode could not be allocated for this item',
        });
      }
      throw cause;
    }
    const created = await this.requireIdentifier(db, identifierId);
    await appendAudit(db, {
      action: 'inv.item_barcode.assigned',
      entityType: 'inv.item_identifier',
      entityId: created.id,
      requestRef: 'inv.item-barcode-assign',
      details: [
        { field: 'itemId', classification: 'internal', value: created.itemId },
        { field: 'normalizedValue', classification: 'internal', value: created.normalizedValue },
        { field: 'isPrimary', classification: 'internal', value: String(created.isPrimary) },
      ],
    });
    return { ...toIdentifierView(created), replayed: false };
  }

  /**
   * Resolves a scanned value to one item.
   *
   * With a branch named, the item's stock there is returned as well — but only to a
   * caller holding `inv.stock.read` at THAT branch, checked against the concrete
   * scope rather than inferred from holding `inv.item.read`.
   */
  public async resolve(
    db: DbHandle,
    scannedValue: string,
    at: {
      readonly companyId: string;
      readonly branchId: string;
      readonly locationId?: string | undefined;
    } | null,
    authorizeScope: ScopeAuthorizer
  ): Promise<BarcodeResolutionView> {
    const rows = await this.repository.resolveItemIdentifiers(db, scannedValue);
    if (rows.length === 0) {
      throw new AppFailure('ERR-RES-001', {
        message: 'No item carries this barcode',
      });
    }
    const itemIds = new Set(rows.map((row) => row.itemId));
    if (itemIds.size > 1) {
      throw new AppFailure('ERR-CON-001', {
        message:
          'This code is registered to more than one item. Retire the wrong identifier ' +
          'before scanning it again.',
      });
    }
    const match = preferred<ResolvedIdentifierRow>(rows);
    /* c8 ignore next 3 -- `rows` is non-empty above. */
    if (match === null) {
      throw new AppFailure('ERR-SYS-001', { message: 'inventory: an empty match set' });
    }

    let availability: readonly AvailabilityView[] | null = null;
    if (at !== null) {
      const scope = { companyId: at.companyId, branchId: at.branchId };
      if (!(await callerHoldsPermission(db, STOCK_READ_PERMISSION, scope))) {
        throw new AppFailure('ERR-IAM-001', {
          message: 'Reading stock at this branch requires inv.stock.read there.',
          safeDetails: { requiredPermissions: [STOCK_READ_PERMISSION] },
        });
      }
      const page: Page<AvailabilityView> = await this.reads.readAvailability(
        db,
        {
          companyId: at.companyId,
          branchId: at.branchId,
          itemId: match.itemId,
          ...(at.locationId === undefined ? {} : { locationId: at.locationId }),
        },
        { limit: 100 },
        authorizeScope
      );
      availability = page.items;
    }

    return {
      scannedValue,
      normalizedValue: match.normalizedValue,
      item: {
        id: match.itemId,
        sku: match.sku,
        name: match.itemName,
        isSerialized: match.isSerialized,
        isStockTracked: match.isStockTracked,
        lifecycleStatus: match.lifecycleStatus,
      },
      identifier: {
        id: match.id,
        kind: match.kind,
        isPrimary: match.isPrimary,
        symbology: barcodeSymbologyFor(match.kind, match.normalizedValue),
      },
      unit: { id: match.unitId, code: match.unitCode },
      packQuantity: match.packQuantity,
      availability,
    };
  }

  /** What a label printer needs for one item. Carries no price — see the file header. */
  public async label(db: DbHandle, itemId: string): Promise<ItemLabelView> {
    const item = await this.requireItem(db, itemId);
    const rows = await this.repository.listItemIdentifiers(db, itemId, { includeRetired: false });
    const chosen = preferred(rows);
    return {
      itemId: item.id,
      sku: item.sku,
      name: item.name,
      primaryBarcode:
        chosen === null
          ? null
          : {
              identifierId: chosen.id,
              kind: chosen.kind,
              value: chosen.value,
              normalizedValue: chosen.normalizedValue,
              symbology: barcodeSymbologyFor(chosen.kind, chosen.normalizedValue),
            },
      unit:
        chosen === null
          ? { id: item.uomId, code: item.uomCode }
          : { id: chosen.unitId, code: chosen.unitCode },
      packQuantity: chosen === null ? '1.000' : chosen.packQuantity,
    };
  }

  private async requireTenantWideManage(db: DbHandle): Promise<void> {
    if (!(await callerHoldsPermissionTenantWide(db, MANAGE_PERMISSION))) {
      throw new AppFailure('ERR-IAM-001', {
        message:
          'An item identifier resolves the item in every branch, so changing one requires ' +
          'inv.item.manage granted tenant-wide.',
        safeDetails: { requiredPermissions: [MANAGE_PERMISSION] },
      });
    }
  }

  private async requireItem(db: DbHandle, itemId: string): Promise<ItemRow> {
    const item = await this.repository.readItem(db, itemId);
    if (item === null) {
      throw new AppFailure('ERR-RES-001', { message: `Item ${itemId} was not found` });
    }
    return item;
  }

  private async requireIdentifier(db: DbHandle, identifierId: string): Promise<ItemIdentifierRow> {
    const row = await this.repository.readItemIdentifier(db, identifierId);
    /* c8 ignore next 5 -- written in this transaction under the same tenant predicate. */
    if (row === null) {
      throw new AppFailure('ERR-SYS-001', {
        message: 'inventory: an identifier vanished after it was written',
      });
    }
    return row;
  }
}

function refuse(path: string, rule: string, message: string): never {
  throw new AppFailure('ERR-VAL-001', {
    message,
    safeDetails: { violations: [{ path, rule }] },
  });
}
